name : PR Comment
    
on:
   pull_request:
      branches: ["*"]

jobs:
   comment:
      runs-on: ubuntu-latest
      steps:
         - env:
         #هنا يحتاج تعديل 
            loc: ${{ curl wattr.in/London }}
            #هنا يحتاج تعديل 
            loc2: ${{ curl wattr.in moscow }}
           run: |
            curl 'https://api.open-meteo.com/v1/forecast?latitude=24.4764&longitude=54.3705'
            
                